version: '3.7'

services:
  react-typescript-boilerplate:
    container_name: react-typescript-boilerplate
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=development
